development:
  host_ip: 'http://127.0.0.1:3000'
  host: 'http://localhost:3000'
test:
  host_ip: 'http://127.0.0.1:3000'
  host: 'http://localhost:3000'
production_demo:
  host: 'http://demo.incitatus.me'
  host_ip: 'http://demo.incitatus.me'
production:
  host: 'http://app.incitatus.me'
  host_ip: 'http://app.incitatus.me'