development:
  consumer_key: HkShJOE3T3ZXFjZLuhV9Q
  consumer_secret: 8U0JtBuzzNT44ylIyVUbIefiqtfUeMET8jTtwqWRqE
test:
  consumer_key: HkShJOE3T3ZXFjZLuhV9Q
  consumer_secret: 8U0JtBuzzNT44ylIyVUbIefiqtfUeMET8jTtwqWRqE
production_demo:
  consumer_key: HkShJOE3T3ZXFjZLuhV9Q
  consumer_secret: 8U0JtBuzzNT44ylIyVUbIefiqtfUeMET8jTtwqWRqE
production:
  consumer_key: HkShJOE3T3ZXFjZLuhV9Q
  consumer_secret: 8U0JtBuzzNT44ylIyVUbIefiqtfUeMET8jTtwqWRqE